name: Build sanity and docs checks

on:
  push:
    branches:
    - master
    - '*.x'
    paths-ignore:
    - '**/*.md'
    - '!SECURITY.md'
  pull_request:
    branches:
    - master
    - '*.x'
    paths-ignore:
    - '**/*.md'
    - '!SECURITY.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanity-checks:
    name: Build sanity and docs checks
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - run: dnf update -y && dnf install -y autoconf make expat-devel openssl-devel libtool zlib-devel gcc-c++ xmlto gawk
      - uses: actions/checkout@v3
      - run: ./autogen.sh
      - run: ./configure --with-ssl=openssl --with-expat --enable-debug
      - run: make -C src check-incl
      - run: make -C src check-c++
      - run: make docs
      - run: cp SECURITY.md /tmp/SECURITY.md.committed
      - run: rm -f SECURITY.md && make SECURITY.md
      - run: diff -u /tmp/SECURITY.md.committed SECURITY.md
